src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use App\Services\ecommerce\Tools;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @Groups({"show_list"})
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Vous devez donner un nom au produit")
     * @Groups({"show_list"})
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @Assert\Choice(callback={"App\Services\ecommerce\Tools", "getTypeTransaction"}, message="Le type de transaction n'est pas défini")
     * @Groups({"show_list"})
     * @ORM\Column(type="string", length=255)
     */
    private $typeTransaction;

    /**
     * @Assert\GreaterThan(value = -1,message="la valeur du prix doit être supérieure à zèro")
     * @Assert\NotBlank(message="Vous devez donner un prix au produit")
     * @Groups({"show_list"})
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @Assert\Range(
     *      min = 0,
     *      max = 100,
     *      notInRangeMessage = "Pourcentage entre {{ min }}% et {{ max }}%",
     * )
     * @Groups({"show_list"})
     * @ORM\Column(type="float", nullable=false)
     */
    private $prixPromo = 0.0;

    /**
     * @Groups({"show_list"})
     * @ORM\Column(type="string", length=255)
     */
    private $images = "a:0:{}";

    /**
     * @Groups({"show_list"})
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $localisation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visiblite = true;

    /**
     * @ORM\Column(type="float")
     */
    private $priorite = 1;

    /**
     * @Groups({"show_list"})
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dureeSejour;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $meuble;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $produitsAssocies = "a:0:{}";

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $attributs = "a:0:{}";

    /**
     * @ORM\Column(type="integer")
     */
    private $nbreConsultations = 0;

    /**
     * @ORM\OneToOne(targetEntity=Caracteristiques::class)
     */
    private $caracteristique;

    /**
     * @ORM\OneToOne(targetEntity=Dimension::class)
     */
    private $dimension;

    /**
     * @Groups({"show_list"})
     * @ORM\OneToOne(targetEntity=Date::class)
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $Client;

    /**
     * @ORM\ManyToOne(targetEntity=Ville::class)
     */
    private $ville;

    /**
     * @ORM\OneToMany(targetEntity=Avis::class, mappedBy="produit")
     */
    private $avis;

    /**
     * @ORM\ManyToOne(targetEntity=CategorieProd::class)
     */
    private $categorieProd;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function __construct()
    {
        $this->avis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param $nbJours
     * @return bool
     */
    public function isValide($nbJours = 60)
    {
        return (($this->getDate()->getDateModification()->diff(new \DateTime())->d) < $nbJours);
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = strtolower($nom);

        return $this;
    }

    public function getTypeTransaction(): ?string
    {
        return $this->typeTransaction;
    }

    public function setTypeTransaction(string $typeTransaction): self
    {
        $this->typeTransaction = strtolower($typeTransaction);

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPrixPromo(): ?float
    {
        return $this->prixPromo;
    }

    public function setPrixPromo(?float $prixPromo): self
    {
        $this->prixPromo = $prixPromo;

        return $this;
    }

    public function getImages(): ?array
    {
        return unserialize($this->images);
    }

    public function setImages(?array $images): self
    {
        $this->images = serialize($images);

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(?string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }

    public function isVisiblite(): ?bool
    {
        return $this->visiblite;
    }

    public function setVisiblite($visiblite): self
    {
        $this->visiblite = $visiblite;

        return $this;
    }

    public function getPriorite(): ?float
    {
        return $this->priorite;
    }

    public function setPriorite(float $priorite): self
    {
        $this->priorite = $priorite;

        return $this;
    }

    public function getDureeSejour(): ?int
    {
        return $this->dureeSejour;
    }

    public function setDureeSejour(?int $dureeSejour): self
    {
        $this->dureeSejour = $dureeSejour;

        return $this;
    }

    public function isMeuble(): ?bool
    {
        return $this->meuble;
    }

    public function setMeuble(?bool $meuble): self
    {
        $this->meuble = $meuble;

        return $this;
    }

    public function getProduitsAssocies(): ?array
    {
        return unserialize($this->produitsAssocies);
    }

    public function setProduitsAssocies(?array $produitsAssocies): self
    {
        $this->produitsAssocies = serialize($produitsAssocies);

        return $this;
    }

    public function getAttributs(): ?array
    {
        return unserialize($this->attributs);
    }

    public function setAttributs(?array $attributs): self
    {
        $this->attributs = serialize($attributs);

        return $this;
    }

    public function getNbreConsultations(): ?int
    {
        return $this->nbreConsultations;
    }

    public function setNbreConsultations(int $nbreConsultations): self
    {
        $this->nbreConsultations = $nbreConsultations;

        return $this;
    }

    public function getCaracteristique(): ?Caracteristiques
    {
        return $this->caracteristique;
    }

    public function setCaracteristique(?Caracteristiques $caracteristique): self
    {
        $this->caracteristique = $caracteristique;

        return $this;
    }

    public function getDimension(): ?Dimension
    {
        return $this->dimension;
    }

    public function setDimension(?Dimension $dimension): self
    {
        $this->dimension = $dimension;

        return $this;
    }

    public function getDate(): ?Date
    {
        return $this->date;
    }

    public function setDate(?Date $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getClient(): ?User
    {
        return $this->Client;
    }

    public function setClient(?User $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection|Avis[]
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis[] = $avi;
            $avi->setProduit($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): self
    {
        if ($this->avis->contains($avi)) {
            $this->avis->removeElement($avi);
            // set the owning side to null (unless already changed)
            if ($avi->getProduit() === $this) {
                $avi->setProduit(null);
            }
        }

        return $this;
    }

    public function getCategorieProd(): ?CategorieProd
    {
        return $this->categorieProd;
    }

    public function setCategorieProd(?CategorieProd $categorieProd): self
    {
        $this->categorieProd = $categorieProd;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/ecommerce/CategorieProdBackController.php
<?php

namespace App\Controller\ecommerce;

use App\Entity\CategorieProd;
use App\Entity\Produit;
use App\Form\ecommerce\CategorieProdType;
use App\Repository\CategorieProdRepository;
use App\Services\ecommerce\Tools;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

/**
 * Class CategorieProdBackController
 * @Route("/back/ecommerce/categories")
 * @package App\Controller\ecommerce
 */
class CategorieProdBackController extends AbstractController
{
    /**
     * page d'accueil des catégories
     *
     * @Route("/", name="category_prod")
     * @param CategorieProdRepository $prodRepository
     * @param Tools $tools
     * @return Response
     */
    public function index(CategorieProdRepository $prodRepository, Tools $tools)
    {
        return $this->render('backend/ecommerce/categrie/categorieProd.html.twig', [
            'categories' => $prodRepository->findAllCategories(),
            'typeProduits' => $tools->getTypeProduit(),
        ]);
    }

    /**
     * sauvegarde les madifications sur les anciennes catégories et les nouvelles
     *
     * @Route("/save/{category}", name="save_category")
     * @param Request $request
     * @param Tools $tools
     * @param CategorieProd|null $category
     * @return JsonResponse | RedirectResponse
     */
    public function saveCategory(Request $request,Tools $tools,CategorieProd $category = null)
    {
        $data = [
            "success" => [],
            "errors" => []
        ];
        $manager = $this->getDoctrine()->getManager();
        $repo = $manager->getRepository(CategorieProd::class);

        if($category==null)
            $category = (new CategorieProd())->setOrdre(0);

        $form = $this->createForm(CategorieProdType::class, $category,[
            'action'=>$this->generateUrl("save_category",["category"=>($category==null)?$category->getId():null]),
        ]);

        /**
         *  modifications sur la dispostion
         */
        $categories = $request->get("categories");

        if ($categories != null) {
            $i = 1;
            foreach ($categories as $cat) {
                $catId = $cat["id"];

                /** @var CategorieProd $category */
                $category = $repo->findOneBy(["id" => $catId]);

                if ($category != null) {
                    $category->setOrdre($i)->setCategorieParent(null);
                    $manager->persist($category);
                    $i++;

                    if (array_key_exists("children", $cat)) {
                        $j = 1;
                        foreach ($cat["children"] as $sc) {
                            $scId = $sc["id"];

                            /** @var CategorieProd $sousCategory */
                            $sousCategory = $repo->findOneBy(["id" => $scId]);
                            if ($sousCategory != null) {
                                if($sousCategory->getTypeCategorie()==$category->getTypeCategorie())
                                {
                                    $sousCategory->setOrdre($j)->setCategorieParent($category)->setTypeCategorie($category->getTypeCategorie());
                                    $manager->persist($sousCategory);
                                    $j++;
                                }
                                else
                                {
                                    array_push($data["errors"],[
                                        "La sous catégorie ".$sousCategory->getNomCategorie()." de type ".$sousCategory->getTypeCategorie(). " ne peut être fille de la catégorie de type ".$category->getTypeCategorie()
                                    ]);
                                }
                            }
                        }
                    }
                }
            }
            if(empty($data["errors"]))
            {
                $manager->flush();

                $data["success"] = ["Catégories modifiées avec succès"];

                $data['form'] = $this->render('backend/ecommerce/categrie/formulaire.html.twig', [
                    'form'=> $form->createView(),
                ]);
            }
            else
                $manager->clear();

            return $this->json($data);
        }
        /**
         *  ajout et modifiation de nouvelles catégories
         */

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            if($category->getCategorieParent())
            {
                if($category->getCategorieParent()->getId()==$category->getId())
                    return $this->json(["errors" => ["Une catégorie ne peut être son propre parent "]]);

                if(!($category->getTypeCategorie() == $category->getCategorieParent()->getTypeCategorie()))
                    return $this->json(["errors"=>["La sous catégorie ".$category->getNomCategorie()." de type ".$category->getTypeCategorie(). " ne peut être fille de la catégorie de type ".$category->getCategorieParent()->getTypeCategorie()]]);
            }
            $manager->persist($category);
            $manager->flush();
        }
        else
            return $this->json(["errors"=>$tools->getFormErrorsTree($form)]);

        return $this->json(["route"=>$this->generateUrl("category_prod")]);
    }

    /**
     * recupère le formulaire twig sous forme d'une chaine de caractères pour ajax ou le rend pour twif
     *
     * @Route("/get_category_template/{type}", name="get_categorie_template")
     * @param Request $request
     * @param CategorieProdRepository $repository
     * @param string $type
     * @return Response
     */
    public function getCategorieTemplate(Request $request, CategorieProdRepository $repository, $type = "string")
    {
        $idCategory = $request->query->get("idCategory", "empty");
        $category = null;

        if($idCategory!="empty")
            $category = $repository->findOneBy(["id" => $idCategory]);
        if ($category == null)
            $category = new CategorieProd();

        $form = $this->createForm(CategorieProdType::class, $category,[
            'action'=>$this->generateUrl("save_category",["category"=>$category->getId()]),
        ]);

        if($type == "twig")
            return $this->render('backend/ecommerce/categrie/formulaire.html.twig', [
                'form'=> $form->createView(),
            ]);

        return $this->json($this->renderView('backend/ecommerce/categrie/formulaire.html.twig', [
            'form'=> $form->createView(),
        ]));
    }

    /**
     * @Route("/delete_category", name="delete_category")
     * @param EntityManagerInterface $em
     * @param Request $request
     * @param CategorieProdRepository $repository
     * @return JsonResponse
     */
    public function DeleteCategorie(EntityManagerInterface $em,Request $request, CategorieProdRepository $repository)
    {
        $data = [
            "errors" => []
        ];
        $idCategory = $request->get("idCategory", null);
        if (!$idCategory)
            die();
        $category = $repository->findOneBy(["id" => $idCategory]);
        if (!$category)
            die();

        if($em->getRepository(Produit::class)->count(["categorieProd"=>$category->getId()])>0)
            $data["errors"] = ["vous devez supprimer tous les produits de cette catégorie"];
        else
        {
            $em->remove($category);
            $em->flush();
        }

        return $this->json($data);
    }

    /**
     * @Route("/get_category", name="get_categorie")
     * @param Request $request
     * @param CategorieProdRepository $repository
     * @return JsonResponse
     */
    public function getCategorie(Request $request, CategorieProdRepository $repository)
    {
        $idCategory = $request->query->get("idCategory", null);
        if (!$idCategory)
            die();

        sleep(3);

        return $this->json($repository->findOneBy(["id" => $idCategory]), 200, [], [
            ObjectNormalizer::CIRCULAR_REFERENCE_HANDLER => function ($object) {
                return $object->getId();
            },
        ]);
    }
}

templates/backend/ecommerce/commande/detail_commande.html.twig
{% extends "backend/base/base.html.twig" %}
{% block stylesheets %}
    <link href="{{ asset('backend/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block title %} Admins {% endblock %}
{% block block_starter %} Admins {% endblock %}
{% block body %}
    <span id="order_id" hidden>{{ order.id }}</span>
    <div class="row">
        <div class="col-xl-4 col-md-6">
            <div class="card-box">
                <div class="text-center">
                    <h4 class="mb-1">Mode de Paiement</h4>
                    <p class="text-muted mb-1">
                        {% if order.payement is same as ("Orange Money") %}
                            <i class="fas fa-money-check-alt" style="color: #0023ff;"></i>
                        {% elseif order.payement is same as ("Paypal") %}
                            <i class="fab fa-cc-paypal" style="color: #0023ff;"></i>
                        {% elseif order.payement is same as ("En Espèce") %}
                            <i class="far fa-money-bill-alt" style="color: #0023ff;"></i>
                        {% endif %} {{order.payement}}
                    </p>
                </div>
            </div>
        </div>
        <!-- end col -->

        <div class="col-xl-4 col-md-6">
            <div class="card-box">
                <div class="text-center">
                    <h4 class="mb-1">Mode de Paiement</h4>
                    <p class="text-muted mb-1"></p>
                    <p class="text-muted mb-1"><i class="fas fa-shipping-fast" style="color: #0023ff;"></i> {{ order.livraison }}</p>
                </div>
            </div>
        </div>
        <!-- end col -->

        <div class="col-xl-4 col-md-6">
            <div class="card-box">
                <div class="text-center">
                    <h4 class="mb-1">Statut</h4>
                    <p class="text-muted mb-1">
                        {% if order.status is same as ("Livré") %}
                            <i class="fas fa-check-square" style="color: #0023ff;"></i>
                        {% elseif order.status is same as ("En cours de Livraison") %}
                            <i class="mdi mdi-dots-horizontal" style="color: #0023ff;"></i>
                        {% elseif order.status is same as ("En Attente") %}
                            <i class="fas fa-window-close" style="color: #0023ff;"></i>
                        {% endif %} {{order.status}}
                    </p>
                </div>
            </div>
        </div>
        <!-- end col -->
    </div>

    <div class="row">
        <div class="col-xl-6">
            <div class="card-box">
                <h4 class="header-title text-center">Informations sur le Client</h4>

                <div class="mt-3 text-left">
                    <p class="text-muted font-15 font-family-secondary mb-0"><span style="color: #0a0a0a;"> Nom : </span> <span>{{ order.client.nom }}</span></p>
                    <p class="text-muted font-15 font-family-secondary mb-0"><span style="color: #0a0a0a;"> Prénom : </span> <span>{{ order.client.prenom }}</span></p>
                    <p class="text-muted font-15 font-family-secondary mb-0"><span style="color: #0a0a0a;"> Email : </span> <span>{{ order.client.email }}</span></p>
                    <p class="text-muted font-15 font-family-secondary mb-0"><span style="color: #0a0a0a;"> Numéro : </span> <span>{{ order.client.telephone }}</span></p>
                    <p class="text-muted font-15 font-family-secondary mb-0">
                        {% set mois = ['Janvier', 'Fevrier','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Decembre'] %}
                        <span style="color: #0a0a0a;"> Date de commande : </span> <span>{{ order.datecom|date('l d-m M - Y H:i:s')}}</span>
                    </p>
                </div>
            </div>
            <!-- end card-box -->
        </div>
        <!-- end col -->

        <div class="col-xl-6">
            <div class="card-box">
                <h4 class="header-title text-center">Informations sur la livraison</h4>

                <div class="mt-3 text-left">
                    <form action="#" class="form-horizontal" hidden>
                        <div class="col-sm-11">
                            <div class="input-group">
                                <span style="color: #0a0a0a;"> Date de Livraison: </span><br />
                                <input type="text" class="form-control date_liv" data-provide="datepicker" data-date-autoclose="true" />
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="ti-calendar"></i></span>
                                </div>
                                <button class="valider button btn-primary"><span class="envoie"></span>Valider</button>
                            </div>
                            <!-- input-group -->
                        </div>
                    </form>

                    {% if order.date_liv is null %}
                        <p class="text-muted font-15 font-family-secondary mb-0">
                            {% set mois = ['Janvier', 'Fevrier','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Decembre'] %}
                            <span style="color: #0a0a0a;" class="show_calendar2"> Date de Livraison : </span> <span class="show_calendar dat_liv">Non définie  </span > <i class="far fa-edit text-right show_calendar" style="color: #0023ff; cursor: pointer"></i>
                        </p>
                    {% else %}
                        <p class="text-muted font-15 font-family-secondary mb-0">
                            {% set mois = ['Janvier', 'Fevrier','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Decembre'] %}
                            <span style="color: #0a0a0a;" class="show_calendar2"> Date de Livraison : </span> <span class="show_calendar dat_liv">{{ order.date_liv|date('l d-m M - Y')}}</span>   <i class="far fa-edit text-right show_calendar" style="color: #0023ff; cursor: pointer"></i>
                        </p>
                    {% endif %}

                    <form action="#" class="form-horizontal2" id="form_liv" hidden>
                        <div class="col-sm-11">
                            <div class="input-group">
                                <table  width="350">
                                    <tr>
                                        <td><span style="color: #0a0a0a;"> Livreur: </span><br /></td>
                                        <td width="250">
                                            <input type="text" class="form-control nom_liv" name="nom_liv"/>
                                            <div class="input-group-append">
                                            </div>
                                        </td>
                                        <td><button class="affecter_liv button btn-primary"><span class="envoie_liv"></span>Valider</button></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td width="250">
                                                <select border="0" id="select_livreur" class="select2 select2-selection--single" multiple="multiple" multiple data-placeholder="Choisir ...">

                                            </select>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <!-- input-group -->
                        </div>
                    </form>

                    {% if order.livreur is null %}
                        <p class="text-muted font-15 font-family-secondary mb-0">
                            <span style="color: #0a0a0a;" class="Livreur"> Livreur : </span> <span class="set_liv liv">Aucun Livreur Affecté</span>   <i class="far fa-edit text-right set_liv" style="color: #0023ff; cursor: pointer"></i>
                        </p>
                        {% else %}
                            <p class="text-muted font-15 font-family-secondary mb-0">
                                <span style="color: #0a0a0a;" class="Livreur"> Livreur : </span> <span class="set_liv liv">{{order.livreur.nom}} {{order.livreur.prenom}}</span>   <i class="far fa-edit text-right set_liv" style="color: #0023ff; cursor: pointer"></i>
                            </p>
                    {% endif %}
                </div>
            </div>
            <!-- end card-box -->
        </div>
        <!-- end col -->
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <div class="responsive-table-plugin">
                        <div class="table-rep-plugin">
                            <div class="table-responsive" data-pattern="priority-columns">
                                <table id="tech-companies-1" class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th data-priority="1">Produit</th>
                                        <th data-priority="3">Quantité</th>
                                        <th data-priority="1">Prix</th>
                                        <th data-priority="3">Propriétaire</th>
                                        <th data-priority="3">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for prod in order.produits %}
                                        <tr>
                                            <th><img src="{{ prod.images }}" alt="" width="90" height="90"></th>
                                            <td>
                                                <p><span style="color: #0a0a0a">Nom : </span>  {{ prod.name }}</p>
                                                <p><span style="color: #0a0a0a">Catégorie :</span>  {{ prod.categorie }}</p>
                                            </td>
                                            <td>{{ prod.quantity }}</td>
                                            <td>
                                                <p><span style="color: #0a0a0a">Prix Promo : </span>  {{ prod.prix-prod.prixpromo }} FCFA</p>
                                                <p><span style="color: #0a0a0a">Prix :</span>  <s>{{ prod.prix }} </s> FCFA</p>
                                            </td>
                                            <td>
                                                <p><span style="color: #0a0a0a">Nom : </span>  {{ prod.proprietaire.nom }}  {{ prod.proprietaire.prenom }}</p>
                                                <p><span style="color: #0a0a0a">Email :</span>  {{ prod.proprietaire.email }}</p>
                                                <p><span style="color: #0a0a0a">Numéro :</span>  {{ prod.proprietaire.telephone }}</p>
                                            </td>
                                            <td>
                                                {{ (prod.prix-prod.prixpromo)*prod.quantity }} FCFA
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div> <!-- end .table-responsive -->

                        </div> <!-- end .table-rep-plugin-->
                    </div> <!-- end .responsive-table-plugin-->
                </div> <!-- end card-box -->
            </div> <!-- end col -->
        </div>
    </div>
{% endblock %} {% block javascripts %}
    <script src="{{ asset('backend/js/pages/ecommerce/order.js') }}"></script>
    <script src="{{ asset('backend/libs/sweetalert2/sweetalert2.min.js') }}"></script>
    <script src="{{ asset('backend/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ asset('backend/libs/clockpicker/bootstrap-clockpicker.min.js') }}"></script>
    <script src="{{ asset('backend/libs/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('backend/libs/moment/moment.min.js') }}"></script>
    <script src="{{ asset('backend/libs/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ asset('backend/js/pages/form-pickers.init.js') }}"></script>
    <script src="{{ asset('backend/libs/rwd-table/rwd-table.min.js') }}"></script>
    <script src="{{ asset('backend/js/pages/responsive-table.init.js') }}"></script>
    <script src="{{ asset('backend/libs/select2/select2.min.js') }}"></script>

{% endblock %}