src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use App\Services\ecommerce\Tools;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $departement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $partenariat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_login;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $local;

    /**
     * @ORM\Column(type="datetime", length=255)
     */
    private $creation;

    /**
     * @ORM\Column(type="blob")
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $boutique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $domaine = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $note;

    /**
     * @ORM\OneToOne(targetEntity=Shipping::class)
     */
    private $livraison;

    /**
     * @ORM\OneToOne(targetEntity=Billing::class)
     */
    private $paiement;

    /**
     * @ORM\Column(type="integer", options={"comment":"enable shipping address"})
     */
    private $esa;

    /**
     * @ORM\Column(type="boolean")
     */
    private $phone_verified;

    /**
     * @ORM\Column(type="text",nullable=true)
     */
    private $packProduct;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"comment":"partner status"})
     */
    private $ps;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"comment":"date partnership"})
     */
    private $dp;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"comment":"admin lock"})
     */
    private $al;

    public function __construct()
    {
        $this->creation = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return bool
     */
    public function isAdmin()
    {
        return in_array("ROLE_ADMIN",$this->getRoles());
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(?string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getPartenariat(): ?string
    {
        return $this->partenariat;
    }

    public function setPartenariat(?string $partenariat): self
    {
        $this->partenariat = $partenariat;

        return $this;
    }

    public function getLastLogin(): ?string
    {
        return $this->last_login;
    }

    public function setLastLogin(?string $last_login): self
    {
        $this->last_login = $last_login;

        return $this;
    }

    public function getLocal(): ?string
    {
        return $this->local;
    }

    public function setLocal(string $local): self
    {
        $this->local = $local;

        return $this;
    }

    public function getCreation(): ?\DateTimeInterface
    {
        return $this->creation;
    }

    public function setCreation(\DateTimeInterface $creation): self
    {
        $this->creation = $creation;

        return $this;
    }

    public function getImage()
    {
        return stream_get_contents($this->image);
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }


    public function getLogo()
    {
        return stream_get_contents($this->logo);
    }

    public function setLogo($logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getBoutique(): ?string
    {
        return $this->boutique;
    }

    public function setBoutique(?string $boutique): self
    {
        $this->boutique = $boutique;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDomaine(): ?array
    {
        return $this->domaine;
    }

    public function setDomaine(?array $domaine): self
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(?string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getLivraison()
    {
        return $this->livraison;
    }

    /**
     * @param mixed $livraison
     */
    public function setLivraison($livraison): void
    {
        $this->livraison = $livraison;
    }

    /**
     * @return mixed
     */
    public function getPaiement()
    {
        return $this->paiement;
    }

    /**
     * @param mixed $paiement
     */
    public function setPaiement($paiement): void
    {
        $this->paiement = $paiement;
    }

    public function getEsa(): ?int
    {
        return $this->esa;
    }

    public function setEsa(int $esa): self
    {
        $this->esa = $esa;

        return $this;
    }

    public function getPackProduct(): array
    {
        return unserialize($this->packProduct);
    }

    public function setPackProduct(array $pack): self
    {
        $this->packProduct = serialize($pack);


        return $this;
    }

    public function getPhoneVerified(): ?bool
    {
        return $this->phone_verified;
    }

    public function setPhoneVerified(bool $phone_verified): self
    {
        $this->phone_verified = $phone_verified;

        return $this;
    }

    public function getPs(): ?bool
    {
        return $this->ps;
    }

    public function setPs(?bool $ps): self
    {
        $this->ps = $ps;

        return $this;
    }

    public function getDp(): ?string
    {
        return $this->dp;
    }

    public function setDp(?string $dp): self
    {
        $this->dp = $dp;

        return $this;
    }

    public function getAl(): ?bool
    {
        return $this->al;
    }

    public function setAl(?bool $al): self
    {

templates/security/backend/admins.html.twig
{% extends "backend/base/base.html.twig" %}

{% block stylesheets %}

{% endblock %}

{% block title %} Admins {% endblock %}
{% block block_starter %} Admins {% endblock %}
{% block body %}

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title">ADMINISTRATEURS</h4>
                <p class="sub-header">
                    Liste des administrateurs de l'application.
                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
                            <div class="form-group mr-2">
                                <button id="demo-btn-addrow" class="btn btn-primary"><i class="mdi mdi-plus-circle mr-2"></i> Add New Admin</button>
                            </div>
                            <div class="form-group">
                                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                        <th data-sort-ignore="true" class="min-width"></th>
                        <th data-sort-initial="true" data-toggle="true">NOm</th>
                        <th>Prenom</th>
                        <th data-hide="phone">Email</th>
                        <th data-hide="phone, tablet">Telephone</th>
                        <th data-hide="phone, tablet">Departement</th>
                        <th data-hide="phone, tablet">Creation</th>
                        <th data-hide="phone, tablet">Vue le</th>
                        <th data-hide="phone, tablet">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for admin in admins %}
                    <tr>
                        <td class="text-center"><span id="id_user" hidden>{{ admin.id }}</span><button class="remove-admin btn btn-danger btn-xs btn-icon"><i class="fa fa-times"></i></button></td>
                        <td>{{admin.nom}}</td>
                        <td>{{admin.prenom}}</td>
                        <td {% if admin.verified == 0 %}style="background-color: #F5275E;color: white;" {% endif %}>{{admin.email}}</td>
                        <td {% if admin.phoneVerified == 0 %}style="background-color: #F5275E;color: white;" {% endif %}>{{admin.telephone}}</td>
                        <td>{{admin.departement}}</td>
                        <td>{{admin.creation|format_datetime()}}</td>
                        <td>{{admin.lastLogin|format_datetime()}}</td>
                        <td>{% if admin.verified == 1 and admin.phoneVerified == 1 %}<span class="badge label-table badge-success">Verifié</span> {% elseif admin.verified == 0 or admin.phoneVerified == 0 %} <span class="badge label-table badge-secondary">En Attente</span> {% else %} <span class="badge label-table badge-danger">Desactivé</span> {% endif %}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <td colspan="9">
                            <div class="text-right">
                                <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>

{% endblock %}

{% block javascripts %}
    <!-- Footable js -->
    <script src="{{ asset('backend/libs/footable/footable.all.min.js') }}"></script>

    <!-- Init js -->
    <script src="{{ asset('backend/js/pages/foo-tables.init.js') }}"></script>
{% endblock %}

templates/security/backend/lock.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>lock screen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{{ asset('backend/images/favicon.ico') }}">

    <!-- App css -->
    <link href="{{ asset('backend/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('backend/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('backend/css/app.min.css') }}" rel="stylesheet" type="text/css" />

</head>

<body class="authentication-bg">

<div class="account-pages mt-5 mb-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                <div class="card">

                    <div class="card-body p-4">

                        <div class="text-center mb-4">
                            <a href="#">
                                <span><img src="{{ asset('backend/images/logo-dark.png') }}" alt="" height="22"></span>
                            </a>
                        </div>

                        <div class="text-center w-75 m-auto">
                            <img src="{{ app.user ? app.user.image }}" alt="user-image" class="rounded-circle avatar-lg img-thumbnail">
                            <h4 class="text-dark-50 text-center mt-3">Salut ! {{ app.user ? app.user.prenom }}</h4>
                            <p class="text-muted mb-4">Entrez votre mot de passe pour accéder à l'interface administrateur.</p>
                        </div>

                        <form action="#">

                            <div class="form-group mb-3">
                                <label for="password">Mot de passe</label></br>
                                <code id="error-message" ></code>
                                <input class="form-control" type="password" required id="lock-screen-password" placeholder="Tapez votre mot de passe">
                            </div>

                            <div class="form-group mb-0 text-center">
                                <button class="btn btn-primary btn-block" id="lock-screen-submit" type="submit"> Se Connecter </button>
                            </div>

                        </form>

                    </div> <!-- end card-body -->
                </div>
                <!-- end card -->

                <div class="row mt-3">
                    <div class="col-12 text-center">
                        <p class="text-muted">ce n'est Pas vous? revenir <a href="{{path('app_logout')}}" class="text-muted font-weight-medium ml-1">se connecter </a>/<a href="{{path('app_logout')}}" class="text-muted font-weight-medium ml-1">interface client</a></p>
                    </div> <!-- end col -->
                </div>
                <!-- end row -->

            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end page -->


<footer class="footer footer-alt">
    2016 - 2019 &copy; Minton theme by <a href="" class="text-muted">Coderthemes</a>
</footer>

<!-- Vendor js -->
<script src="{{ asset('backend/js/vendor.min.js') }}"></script>

<!-- App js -->
<script src="{{ asset('backend/js/app.min.js') }}"></script>

<!-- toastr init js-->
<script src="{{ asset('backend/js/pages/toastr.init.js') }}"></script>

<script>
    $('#lock-screen-submit').on('click', function (event) {
        event.preventDefault();
        const button = document.getElementById('lock-screen-submit');
        $('#error-message').html("");
        var $this = $(this);
        button.disabled = true;
        $('#lock-screen-submit').html("<span class=\"spinner-grow spinner-grow-sm mr-1\" role=\"status\" aria-hidden=\"true\"></span>");
        var form = $('#partenariat-boutique-form');
        $this.addClass('is-loading');
        $.ajax({
            type: "POST",
            url: form.attr("{{path('app_lock')}}"),
            data: {
                "password": $('#lock-screen-password').val(),
            },
            dataType: 'json',
            success: function (data,i) {

                if(data['infos'] === "ok")
                {
                    window.location.href = '/back/';
                }
                else if(data['infos'] === "NaN")
                {
                    $('#error-message').html("Mot de passe incorrect!");
                    $('#lock-screen-submit').html("Se Connecter");
                    $('#lock-screen-password').val("");
                    button.disabled = false;
                }

            },
            error: function (data) {
                button.disabled = false;

            },
        });
    })
</script>

</body>
</html>

templates/security/backend/partners.html.twig
{% extends "backend/base/base.html.twig" %}

{% block stylesheets %}

{% endblock %}

{% block title %} Partners {% endblock %}
{% block block_starter %} Partners {% endblock %}
{% block body %}

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title">PARTENARIAT</h4>
                <p class="sub-header">
                    Liste des partenaires de l'application.
                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
                            <div class="form-group mr-2">
                                <button id="demo-btn-addrow" class="btn btn-primary"><i class="mdi mdi-plus-circle mr-2"></i> Add New Partner</button>
                            </div>
                            <div class="form-group">
                                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                        <th data-sort-ignore="true" class="min-width"></th>
                        <th data-sort-initial="true" data-toggle="true">Nom</th>
                        <th>Prenom</th>
                        <th data-hide="phone">Email</th>
                        <th data-hide="phone, tablet">Telephone</th>
                        <th data-hide="phone, tablet">Creation</th>
                        <th data-hide="phone, tablet">Vue le</th>
                        <th data-hide="phone, tablet">Partenariat</th>
                        <th data-hide="phone, tablet">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for partner in partners %}
                    <tr>
                        <td class="text-center" id="row_etat{{ partner.id }}"><span id="id_user" hidden>{{ partner.id }}</span>{% if partner.ps == 0 %} <button class="enable-partner btn btn-success btn-xs btn-icon"><i class="fa fa-check"></i></button> {% elseif partner.ps == 1 %} <button class="disable-partner btn btn-danger btn-xs btn-icon"><i class="fa fa-times"></i></button> {% endif %}</td>
                        <td>{{ partner.nom }}</td>
                        <td>{{ partner.prenom }}</td>
                        <td {% if partner.verified == 0 %}style="background-color: #F5275E;color: white;" {% endif %}>{{partner.email}}</td>
                        <td {% if partner.phoneVerified == 0 %}style="background-color: #F5275E;color: white;" {% endif %}>{{partner.telephone}}</td>
                        <td>{{partner.dp|format_datetime()}}</td>
                        <td>{{partner.lastLogin|format_datetime()}}</td>
                        <td>{{partner.partenariat}}</td>
                        <td>{% if partner.verified == 1 and partner.phoneVerified == 1 %}<span class="badge label-table badge-success">Verifié</span> {% elseif partner.verified == 0 or partner.phoneVerified == 0 %} <span class="badge label-table badge-secondary">En Attente</span> {% else %} <span class="badge label-table badge-danger">Desactivé</span> {% endif %}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <td colspan="9">
                            <div class="text-right">
                                <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>

{% endblock %}

{% block javascripts %}
    <!-- Footable js -->
    <script src="{{ asset('backend/libs/footable/footable.all.min.js') }}"></script>

    <!-- Init js -->
    <script src="{{ asset('backend/js/pages/foo-tables.init.js') }}"></script>
{% endblock %}

templates/security/backend/users.html.twig
{% extends "backend/base/base.html.twig" %}

{% block stylesheets %}

{% endblock %}

{% block title %} Users {% endblock %}
{% block block_starter %} Users {% endblock %}
{% block body %}

    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <h4 class="header-title">UTILISATEURS</h4>
                <p class="sub-header">
                    Liste de tous utilisateurs inscrits.
                </p>

                <div class="mb-2">
                    <div class="row">
                        <div class="col-12 text-sm-center form-inline">
                            <div class="form-group mr-2">
                                <select id="demo-foo-filter-status" class="custom-select custom-select-sm">
                                    <option value="">Tout</option>
                                    <option value="Validé">Validé</option>
                                    <option value="En Attente">En Attente</option>
                                    <option value="Non Verifié">Non Verifié</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input id="demo-foo-search" type="text" placeholder="Search" class="form-control form-control-sm" autocomplete="on">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <table id="demo-foo-filtering" class="table table-bordered toggle-circle mb-0" data-page-size="7">
                        <thead>
                        <tr>
                            <th data-toggle="true">Nom</th>
                            <th>Prenom</th>
                            <th data-hide="phone">Email</th>
                            <th data-hide="phone, tablet">Telephone</th>
                            <th data-hide="phone, tablet">Creation</th>
                            <th data-hide="phone, tablet">Vue le</th>
                            <th data-hide="phone, tablet">Partenariat</th>
                            <th data-hide="phone, tablet">Promouvoir</th>
                            <th data-hide="phone, tablet">Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{user.nom}}</td>
                            <td>{{user.prenom}}</td>
                            <td {% if user.verified == 0 %}style="background-color: #F5275E;color: white;" {% endif %}>{{user.email}}</td>
                            <td {% if user.phoneVerified == 0 %}style="background-color: #F5275E;color: white;" {% endif %}>{{user.telephone}}</td>
                            <td>{{user.creation|format_datetime()}}</td>
                            <td>{{user.lastLogin|format_datetime()}}</td>
                            <td>{% if user.partenariat %} Partenariat {{ user.partenariat }} {% else %} Aucun partenariat {% endif %}</td>
                            <td class="text-center" id="row_promotion{{ user.id }}">{% if "ROLE_PARTENAIRE" in user.roles %} Ne peut être promu {% else %}<span id="id_user" hidden>{{ user.id }}</span>{% if user.departement %} Promu administrateur e-{{ user.departement }} {% else %}<button class="btn btn-success btn-xs btn-icon" data-id="{{user.id}}" id="promote_user_boutique"><i class="fa fa-shopping-bag"></i></button><button class="btn btn-success btn-xs btn-icon" data-id="{{user.id}}" id="promote_user_services"><i class="fa fa-handshake"></i></button><button class="btn btn-success btn-xs btn-icon" data-id="{{user.id}}" id="promote_user_terrain"><i class="fa fa-map"></i></button>{% endif %}{% endif %}</td>
                            <td>{% if user.verified == 1 and user.phoneVerified == 1 %}<span class="badge label-table badge-success">Validé</span>{% elseif user.verified == 0 and user.phoneVerified == 0  %} <span class="badge label-table badge-danger">Non Verifié</span> {% else %} <span class="badge label-table badge-secondary">En Attente</span> {% endif %}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr class="active">
                            <td colspan="9">
                                <div class="text-right">
                                    <ul class="pagination pagination-rounded justify-content-end footable-pagination m-t-10 mb-0"></ul>
                                </div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div> <!-- end .table-responsive-->
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>

{% endblock %}

{% block javascripts %}
    <!-- Footable js -->
    <script src="{{ asset('backend/libs/footable/footable.all.min.js') }}"></script>

    <!-- Init js -->
    <script src="{{ asset('backend/js/pages/foo-tables.init.js') }}"></script>

    <!-- Sweet alert init js-->
    <script src="{{ asset('backend/js/pages/sweet-alerts.init.js') }}"></script>

{% endblock %}